In [2]:
import numpy as np
n_neighbors = [int(x) for x in np.linspace(start = 1, stop = 500, num = 100)]

In [3]:
n_neighbors

[1,
 6,
 11,
 16,
 21,
 26,
 31,
 36,
 41,
 46,
 51,
 56,
 61,
 66,
 71,
 76,
 81,
 86,
 91,
 96,
 101,
 106,
 111,
 116,
 121,
 127,
 132,
 137,
 142,
 147,
 152,
 157,
 162,
 167,
 172,
 177,
 182,
 187,
 192,
 197,
 202,
 207,
 212,
 217,
 222,
 227,
 232,
 237,
 242,
 247,
 253,
 258,
 263,
 268,
 273,
 278,
 283,
 288,
 293,
 298,
 303,
 308,
 313,
 318,
 323,
 328,
 333,
 338,
 343,
 348,
 353,
 358,
 363,
 368,
 373,
 379,
 384,
 389,
 394,
 399,
 404,
 409,
 414,
 419,
 424,
 429,
 434,
 439,
 444,
 449,
 454,
 459,
 464,
 469,
 474,
 479,
 484,
 489,
 494,
 500]